const translations = {
  fr: {
    Envoyer: "Envoyer",
    Search: "Search",
    Découvrez_le_monde_avec_notre_agence_de_voyage: "Découvrez le monde avec notre agence de voyage",
    Des_destinations_exotiques_vous_attendent: "Des destinations exotiques vous attendent. Réservez votre aventure dès aujourd'hui!",
    Voir_les_offres: "Voir les offres",
    english: "English",
    Mexique: "Mexique",
    Entrez_votre_nom: "Entrez votre nom",
    Nos_offres_spéciales_sont_internationales: "Nos_offres_spéciales_sont_internationales",
    Egypt: "Egypt",
    DH: "DH",
    nom: "Nom",
    french: "French",
    arabic: "Arabic",
    votre_email: "votre email",
    Votre_message: "Votre message",
    Agence_Voyage_Bara_Tous_droits_réservés: "2023 Agence Voyage Bara. Tous droits réservés",
    Votre_nom: "Votre nom",
    Vous_pouvez_également_nous_contacter_directement: "Vous pouvez également nous contacter directement",
    Social_Media: "Social Media",
    Message: "Message",
    Adresse_Email: "Adresse Email",
    Contactez_nous: "Contactez-nous",
    Contact: "Contact",
    Offres_spéciales: "Offres spéciales",
    Destinations: "Destinations",
    Accueil: "Accueil",
    Choisissez_une_méthode_de_Paiement: "Choisissez une méthode de Paiement",
    Pour_les_voyages_intérieurs: "Pour les voyages intérieurs",
    Réservez_dès_maintenant: "Réservez dès maintenant",
    Lieu_de_départ: "Lieu de départ",
    Rabat: "Rabat",
    Casablanca: "Casablanca",
    Fes: "Fes",
    Marrakech: "Marrakech",
    Tangier: "Tangier",
    Agadir: "Agadir",
    Meknes: "Meknes",
    Oujda: "Oujda",
    Kenitra: "Kenitra",
    Tetouan: "Tetouan",
    Essaouira: "Essaouira",
    Nador: "Nador",
    Beni_Mellal: "Beni Mellal",
    El_Jadida: "El Jadida",
    Taza: "Taza",
    Safi: "Safi",
    Mohammedia: "Mohammedia",
    Larache: "Larache",
    Settat: "Settat",
    Ksar_El_Kebir: "Ksar El Kebir",
    Guelmim: "Guelmim",
    Khenifra: "Khenifra",
    Taroudant: "Taroudant",
    Khouribga: "Khouribga",
    Sidi_Slimane: "Sidi Slimane",
    Errachidia: "Errachidia",
    Tiznit: "Tiznit",
    Chefchaouen: "Chefchaouen",
    Al_Hoceima: "Al Hoceima",
    Midelt: "Midelt",
    Azrou: "Azrou",
    Taourirt: "Taourirt",
    Tan_Tan: "Tan-Tan",
    Sefrou: "Sefrou",
    Youssoufia: "Youssoufia",
    Tarfaya: "Tarfaya",
    Tata: "Tata",
    Merzouga: "Merzouga",
    Dakhla: "Dakhla",
    Al_Kuwayra: "Al-Kuwayra",
    Kacem: "Kacem",
    Berkane: "Berkane",
    Ouarzazate: "Ouarzazate",
    Laayoune: "Laayoune",
    Lieu_d_arrivée: "Lieu d'arrivée",
    Nombre_de_personne: "Nombre de personne",
    Nombre_de_bagages: "Nombre de bagages",
    Nombre_d_enfants: "Nombre d'enfants",
    Select_a_Payment_method: "Select a Payment method",
    Need_Help: "Need Help?",
    Pour_les_voyages_internationaux: "Pour les voyages internationaux",
    Japon: "Japon",
    Asie: "Asie",
    Chine: "Chine",
    Thaïlande: "Thaïlande",
    Singapour: "Singapour",
    Bahreïn: "Bahreïn",
    Inde: "Inde",
    Malaisie: "Malaisie",
    Viêt_Nam: "Viêt Nam",
    Corée_du_Sud: "Corée du Sud",
    Maldives: "Maldives",
    Émirats_Arabes_Unis: "Émirats Arabes Unis",
    Arabie_Saoudite: "Arabie Saoudite",
    Afrique: "Afrique",
    Egypte: "Egypte",
    Afrique_du_Sud: "Afrique du Sud",
    Maroc: "Maroc",
    Algérie: "Algérie",
    Tunisie: "Tunisie",
    Amérique_du_Nord: "Amérique du Nord",
    États_Unis_dAmérique: "États-Unis d'Amérique",
    Canada: "Canada",
    Océanie: "Océanie",
    Antarctique: "Antarctique",
    Europe: "Europe",
    Amérique_du_Sud: "Amérique du Sud",
    Nouvelle_Zélande: "Nouvelle-Zélande",
    Pérou: "Pérou",
    Argentine: "Argentine",
    Colombie: "Colombie",
    Brésil: "Brésil",
    Croatie: "Croatie",
    Suisse: "Suisse",
    Norvège: "Norvège",
    Hollande: "Hollanda",
    Portugal: "Portugal",
    Danemark: "Danemark",
    Belgique: "Belgique",
    Autriche: "Autriche",
    Suède: "Suède",
    Grèce: "Grèce",
    Russie: "Russie",
    Allemagne: "Allemagne",
    Royaume_Uni: "Royaume-Uni",
    Turquie: "Turquie",
    Espagne: "Espagne",
    Italie: "Italie",
    France: "France",
    England: "England",
    Maroc_Guelmim: "Maroc-Guelmim",
    Qatar: "Qatar",
    Maroc_Marackech: "Maroc-Marackech",
    Maroc_Rabat: "Maroc-Rabat",
    Nos_offres_spéciales_localement: "Nos offres spéciales localement",
    Maroc_Laayoune: "Maroc-Laayoune",
    Maroc_Dakhla: "Maroc-Dakhla",
    Maroc_Tanger: "Maroc-Tanger",
    Maroc_Agadir: "Maroc-Agadir",
    Spain: "Spain",
    Nos_destinations_populaires_pour_les_voyages_internationaux: "Nos destinations populaires pour les voyages internationaux",
    Maroc_Chefchaouen: "Maroc-Chefchaouen",
    Maroc_Tata: "Maroc-Tata",
    Maroc_Tetouan: "Maroc-Tetouan",
    Maroc_Ifrane: "Maroc-Ifrane",
    Maroc_Casablanca: "Maroc-Casablanca",
    Nos_destinations_populaires_pour_les_voyages_intérieurs: "Nos destinations populaires pour les voyages intérieurs",
    Voir_plus: "Voir plus",
    Nos_Offres_spéciales_Populaires: "Nos Offres spéciales Populaires",
    Nos_Destinations_Populaires: "Nos Destinations Populaires",
  },
  ar: {
    Envoyer: "يرسل",
    french: "الفرنسية",
    Search: "بحث",
    Découvrez_le_monde_avec_notre_agence_de_voyage: "اكتشف العالم مع وكالة السفر لدينا",
    Des_destinations_exotiques_vous_attendent: "وجهات غريبة في انتظاركم. احجز مغامرتك اليوم!",
    Voir_les_offres: "انظر العروض",
    english: "الانجليزية",
    Entrez_votre_nom: "اسمك",
    Egypt: "مصر",
    nom: "الاسم",
    votre_email: "بريدك الإلكتروني",
    Nos_offres_spéciales_sont_internationales: "عروضنا الخاصة عالمية",
    Votre_message: "رسالتك",
    DH: "درهم",
    Votre_nom: "اسمك",
    arabic: "العربية",
    Agence_Voyage_Bara_Tous_droits_réservés: "2023 وكالة بارا للسفريات. جميع الحقوق محفوظة",
    Vous_pouvez_également_nous_contacter_directement: "كما يمكنك الاتصال بنا مباشرة",
    Social_Media: "وسائل التواصل الاجتماعي",
    Message: "رسالة",
    Adresse_Email: "البريد الإلكتروني",
    Contactez_nous: "اتصل بنا",
    Contact: "اتصال",
    Offres_spéciales: "عروض خاصة",
    Destinations: "الأماكن",
    Accueil: "ترحيب",
    Choisissez_une_méthode_de_Paiement: "اختر طريقة الدفع",
    Pour_les_voyages_intérieurs: "للسفر الداخلي",
    Réservez_dès_maintenant: "احجز الآن",
    Lieu_de_départ: "مكان الانطلاق",
    Rabat: "الرباط",
    Casablanca: "الدار البيضاء",
    Fes: "فاس",
    Marrakech: "مراكش",
    Tangier: "طنجة",
    Agadir: "أغادير",
    Meknes: "مكناس",
    Oujda: "وجدة",
    Kenitra: "القنيطرة",
    Tetouan: "تطوان",
    Essaouira: "الصويرة",
    Nador: "الناظور",
    Beni_Mellal: "بني ملال",
    El_Jadida: "الجديدة",
    Taza: "تازة",
    Safi: "آسفي",
    Mohammedia: "المحمدية",
    Larache: "العرائش",
    Settat: "سطات",
    Ksar_El_Kebir: "القصر الكبير",
    Guelmim: "كلميم",
    Khenifra: "خنيفرة",
    Taroudant: "تارودانت",
    Khouribga: "خريبكة",
    Sidi_Slimane: "سيدي سليمان",
    Errachidia: "الرشيدية",
    Tiznit: "تزنيت",
    Chefchaouen: "شفشاون",
    Al_Hoceima: "الحسيمة",
    Midelt: "ميدلت",
    Azrou: "أزرو",
    Taourirt: "تاوريرت",
    Tan_Tan: "تان تان",
    Sefrou: "صفرو",
    Youssoufia: "اليوسفية",
    Tarfaya: "طرفاية",
    Tata: "تاتا",
    Merzouga: "مرزوكة",
    Dakhla: "الداخلة",
    Al_Kuwayra: "الكويرة",
    Kacem: "قاسم",
    Berkane: "بركان",
    Ouarzazate: "ورزازات",
    Laayoune: "العيون",
    Lieu_d_arrivée: "نقطة الوصول",
    Nombre_de_personne: "عدد الاشخاص",
    Nombre_de_bagages: "عدد الحقائب",
    Nombre_d_enfants: "عدد الاطفال",
    Select_a_Payment_method: "اختر طريقة الدفع",
    Need_Help: "تحتاج مساعدة؟",
    Pour_les_voyages_internationaux: "للسفر الدولي",
    Japon: "اليابان",
    Asie: "آسيا",
    Chine: "الصين",
    Thaïlande: "تايلاند",
    Singapour: "سنغافورة",
    Bahreïn: "البحرين",
    Inde: "الهند",
    Malaisie: "ماليزيا",
    Viêt_Nam: "فيتنام",
    Corée_du_Sud: "كوريا الجنوبية",
    Maldives: "جزر المالديف",
    Émirats_Arabes_Unis: "السعودية",
    Arabie_Saoudite: "الإمارات",
    Afrique: "أفريقيا",
    Egypte: "Egypte",
    Afrique_du_Sud: "إفريقيا الجنوبية",
    Maroc: "المملكة المغربية",
    Algérie: "الجزائر",
    Tunisie: "تونس",
    Amérique_du_Nord: "أمريكا الشمالية",
    États_Unis_dAmérique: "أمريكا",
    Canada: "كندا",
    Océanie: "أوقيانوسيا",
    Antarctique: "القطب الجنوبي",
    Europe: "أوروبا",
    Amérique_du_Sud: "أمريكا الجنوبية",
    Nouvelle_Zélande: "زيلاندا الجديدة",
    Australie: "أستراليا",
    Pérou: "بيرو",
    Argentine: "الأرجنتين",
    Colombie: "كولومبيا",
    Brésil: "البرازيل",
    Croatie: "كرواتيا",
    Suisse: "سويسرا",
    Norvège: "النرويج",
    Hollande: "هولاندا",
    Portugal: "البرتغال",
    Danemark: "الدنمارك",
    Belgique: "بلجيكا",
    Autriche: "النمسا",
    Suède: "السويد",
    Grèce: "اليونان",
    Russie: "روسيا",
    Allemagne: "ألمانيا",
    Royaume_Uni: "المملكة المتحدة",
    Turquie: "تركيا",
    Espagne: "إسبانيا",
    Italie: "إيطاليا",
    France: "فرنسا",
    England: "إنكلترا",
    Maroc_Guelmim: "المغرب-كلميم",
    Qatar: "قطر",
    Maroc_Marackech: "المغرب-مراكش",
    Maroc_Rabat: "المغرب-الرباط",
    Nos_offres_spéciales_localement: "عروضنا المميزة محليا",
    Maroc_Laayoune: "المغرب-العيون",
    Maroc_Dakhla: "المغرب-الداخلة",
    Maroc_Tanger: "المغرب-طنجة",
    Maroc_Agadir: "المغرب-أغادير",
    Spain: "إسبانيا",
    Nos_destinations_populaires_pour_les_voyages_internationaux: "وجهاتنا الشعبية للسفر الدولي",
    Maroc_Chefchaouen: "المغرب-شفشاون",
    Maroc_Tata: "المغرب طاطا",
    Maroc_Tetouan: "المغرب-تطوان",
    Maroc_Ifrane: "المغرب-إفران",
    Maroc_Casablanca: "المغرب-الدار البيضاء",
    Nos_destinations_populaires_pour_les_voyages_intérieurs: "وجهاتنا الشعبية للسفر الداخلي",
    Voir_plus: "شاهد المزيد",
    Nos_Offres_spéciales_Populaires: "عروضنا الخاصة الشهيرة",
    Nos_Destinations_Populaires: "وجهاتنا الشعبية",
    Mexique: "مكسيك",
  },
  en: {
    Envoyer: "Send",
    Search: "Search",
    Découvrez_le_monde_avec_notre_agence_de_voyage: "Discover the world with our travel agency",
    Des_destinations_exotiques_vous_attendent: "Exotic destinations await you. Book your adventure today!",
    Voir_les_offres: "See the offers",
    english: "English",
    Mexique: "Mexico",
    Entrez_votre_nom: "Enter your name",
    Nos_offres_spéciales_sont_internationales: "Our special offers are international",
    Egypt: "Egypt",
    DH: "DH",
    nom: "name",
    french: "French",
    arabic: "Arabic",
    votre_email: "your email",
    Votre_message: "Your message",
    Agence_Voyage_Bara_Tous_droits_réservés: "2023 Agence Voyage Bara. All rights reserved",
    Votre_nom: "Your name",
    Vous_pouvez_également_nous_contacter_directement: "You can also contact us directly",
    Social_Media: "Social Media",
    Message: "Message",
    Adresse_Email: "Email Address",
    Contactez_nous: "Contact us",
    Contact: "Contact",
    Offres_spéciales: "Special offers",
    Destinations: "Destinations",
    Accueil: "Home",
    Choisissez_une_méthode_de_Paiement: "Choose a Payment method",
    Pour_les_voyages_intérieurs: "For inward journeys",
    Réservez_dès_maintenant: "Book now",
    Lieu_de_départ: "Departure location",
    Rabat: "Rabat",
    Casablanca: "Casablanca",
    Fes: "Fes",
    Marrakech: "Marrakech",
    Tangier: "Tangier",
    Agadir: "Agadir",
    Meknes: "Meknes",
    Oujda: "Oujda",
    Kenitra: "Kenitra",
    Tetouan: "Tetouan",
    Essaouira: "Essaouira",
    Nador: "Nador",
    Beni_Mellal: "Beni Mellal",
    El_Jadida: "El Jadida",
    Taza: "Taza",
    Safi: "Safi",
    Mohammedia: "Mohammedia",
    Larache: "Larache",
    Settat: "Settat",
    Ksar_El_Kebir: "Ksar El Kebir",
    Guelmim: "Guelmim",
    Khenifra: "Khenifra",
    Taroudant: "Taroudant",
    Khouribga: "Khouribga",
    Sidi_Slimane: "Sidi Slimane",
    Errachidia: "Errachidia",
    Tiznit: "Tiznit",
    Chefchaouen: "Chefchaouen",
    Al_Hoceima: "Al Hoceima",
    Midelt: "Midelt",
    Azrou: "Azrou",
    Taourirt: "Taourirt",
    Tan_Tan: "Tan-Tan",
    Sefrou: "Sefrou",
    Youssoufia: "Youssoufia",
    Tarfaya: "Tarfaya",
    Tata: "Tata",
    Merzouga: "Merzouga",
    Dakhla: "Dakhla",
    Al_Kuwayra: "Al-Kuwayra",
    Kacem: "Kacem",
    Berkane: "Berkane",
    Ouarzazate: "Ouarzazate",
    Laayoune: "Laayoune",
    Lieu_d_arrivée: "Place of arrival",
    Nombre_de_personne: "Number of people",
    Nombre_de_bagages: "Number of baggage",
    Nombre_d_enfants: "Number of children",
    Select_a_Payment_method: "Select a Payment method",
    Need_Help: "Need Help?",
    Pour_les_voyages_internationaux: "For international travel",
    Japon: "Japan",
    Asie: "Asia",
    Chine: "China",
    Thaïlande: "Thailand",
    Singapour: "Singapore",
    Bahreïn: "Bahrain",
    Inde: "India",
    Malaisie: "Malaysia",
    Viêt_Nam: "Vietnam",
    Corée_du_Sud: "South Korea",
    Maldives: "Maldives",
    Émirats_Arabes_Unis: "United Arab Emirates",
    Arabie_Saoudite: "Saudi Arabia",
    Afrique: "Africa",
    Egypte: "Egypt",
    Afrique_du_Sud: "South Africa",
    Maroc: "Morocco",
    Algérie: "Algeria",
    Tunisie: "Tunisia",
    Amérique_du_Nord: "North America",
    États_Unis_dAmérique: "United States of America",
    Canada: "Canada",
    Océanie: "Oceania",
    Antarctique: "Antarctica",
    Europe: "Europe",
    Amérique_du_Sud: "South America",
    Nouvelle_Zélande: "New Zealand",
    Pérou: "Peru",
    Argentine: "Argentina",
    Colombie: "Colombia",
    Brésil: "Brazil",
    Croatie: "Croatia",
    Suisse: "Switzerland",
    Norvège: "Norway",
    Hollande: "Hollanda",
    Portugal: "Portugal",
    Danemark: "Denmark",
    Belgique: "Belgium",
    Autriche: "Austria",
    Suède: "Sweden",
    Grèce: "Greece",
    Russie: "Russia",
    Allemagne: "Germany",
    Royaume_Uni: "United Kingdom",
    Turquie: "Türkiye",
    Espagne: "Spain",
    Italie: "Italy",
    France: "France",
    England: "England",
    Maroc_Guelmim: "Morocco-Guelmim",
    Qatar: "Qatar",
    Maroc_Marackech: "Morocco-Marackech",
    Maroc_Rabat: "Morocco-Rabat",
    Nos_offres_spéciales_localement: "Our special offers locally",
    Maroc_Laayoune: "Morocco-Laayoune",
    Maroc_Dakhla: "Morocco-Dakhla",
    Maroc_Tanger: "Morocco-Tangier",
    Maroc_Agadir: "Morocco-Agadir",
    Spain: "Spain",
    Nos_destinations_populaires_pour_les_voyages_internationaux: "Our popular destinations for international travel",
    Maroc_Chefchaouen: "Morocco-Chefchaouen",
    Maroc_Tata: "Morocco-Tata",
    Maroc_Tetouan: "Morocco-Tetouan",
    Maroc_Ifrane: "Morocco-Ifrane",
    Maroc_Casablanca: "Morocco-Casablanca",
    Nos_destinations_populaires_pour_les_voyages_intérieurs: "Our popular destinations for domestic travel",
    Voir_plus: "See more",
    Nos_Offres_spéciales_Populaires: "Our Popular Special Offers",
    Nos_Destinations_Populaires: "Our Popular Destinations",
  },
};




const languageSelector = document.querySelector("select");
languageSelector.addEventListener("change", (event) => {
  setLanguage(event.target.value);
  localStorage.setItem("lang", event.target.value);
});

document.addEventListener("DOMContentLoaded", () => {
  const language = localStorage.getItem("lang") || "fr"; // اذا لم تكن اللغة متوفرة استخدم الانجليزية
  setLanguage(language);
});

const setLanguage = (language) => {
  const elements = document.querySelectorAll("[data-i18n]");
  elements.forEach((element) => {
    const translationKey = element.getAttribute("data-i18n");
    element.textContent = translations[language][translationKey];
  });
  document.dir = language === "ar" ? "rtl" : "ltr";
};
